version: '3.7'

services:
  db:
    image: postgres:13
    container_name: db-container
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rentx
    volumes:
      - rentx_data:/var/lib/postgresql/data
    network_mode: host
  # api:
  #   image: node:14
  #   container_name: api-container
  #   working_dir: /usr/app
  #   restart: on-failure
  #   command: bash -c "npm install && npm run dev"
  #   volumes:
  #     - .:/usr/app
  #     # - ./package.json:/usr/app/package.json
  #   network_mode: host

volumes:
  rentx_data:
