version: '3.7'

services:
  db:
    image: postgres:13
    container_name: db-container
    restart: on-failure
    environment:
      POSTGRES_USER: rentx
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: rentx
    volumes:
      - rentx_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - rentx-app

volumes:
  rentx_data:

networks:
  rentx-app:
