version: '3.7'

services:
  db:
    image: postgres:13
    container_name: db-container
    restart: on-failure
    environment:
      POSTGRES_USER: rentx
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: rentx
    volumes:
      - rentx_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - rentx-app

  api:
    image: node:14
    container_name: api-container
    working_dir: /app
    restart: on-failure
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./:/app
    ports:
      - 3333:3333
      - 9229:9229
    networks:
      - rentx-app
    depends_on:
      - db

volumes:
  rentx_data:

networks:
  rentx-app:
